services:
  - type: web
    name: bulk-email-sending-system
    env:  python
    plan: free
    buildCommand: pip install -r requirements.txt && python Email/manage.py collectstatic --noinput
    startCommand: gunicorn Email. wsgi --log-file - --bind 0.0.0.0:$PORT
    envVars:
      - key:  PYTHON_VERSION
        value: "3.11"
      - key: DEBUG
        value: "False"
      - key:  ALLOWED_HOSTS
        fromService: 
          name: bulk-email-sending-system
          property: host